/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppLedgerRouteImport } from './routes/_app.ledger'
import { Route as AppInvoicingRouteImport } from './routes/_app.invoicing'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDealersRouteImport } from './routes/_app.dealers'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicingRoute = AppInvoicingRouteImport.update({
  id: '/invoicing',
  path: '/invoicing',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDealersRoute = AppDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dealers': typeof AppDealersRoute
  '/employees': typeof AppEmployeesRoute
  '/expenses': typeof AppExpensesRoute
  '/finance': typeof AppFinanceRoute
  '/inventory': typeof AppInventoryRoute
  '/invoicing': typeof AppInvoicingRoute
  '/ledger': typeof AppLedgerRoute
  '/products': typeof AppProductsRoute
  '/purchases': typeof AppPurchasesRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dealers': typeof AppDealersRoute
  '/employees': typeof AppEmployeesRoute
  '/expenses': typeof AppExpensesRoute
  '/finance': typeof AppFinanceRoute
  '/inventory': typeof AppInventoryRoute
  '/invoicing': typeof AppInvoicingRoute
  '/ledger': typeof AppLedgerRoute
  '/products': typeof AppProductsRoute
  '/purchases': typeof AppPurchasesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/dealers': typeof AppDealersRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/invoicing': typeof AppInvoicingRoute
  '/_app/ledger': typeof AppLedgerRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/dealers'
    | '/employees'
    | '/expenses'
    | '/finance'
    | '/inventory'
    | '/invoicing'
    | '/ledger'
    | '/products'
    | '/purchases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/dealers'
    | '/employees'
    | '/expenses'
    | '/finance'
    | '/inventory'
    | '/invoicing'
    | '/ledger'
    | '/products'
    | '/purchases'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/dealers'
    | '/_app/employees'
    | '/_app/expenses'
    | '/_app/finance'
    | '/_app/inventory'
    | '/_app/invoicing'
    | '/_app/ledger'
    | '/_app/products'
    | '/_app/purchases'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger': {
      id: '/_app/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoicing': {
      id: '/_app/invoicing'
      path: '/invoicing'
      fullPath: '/invoicing'
      preLoaderRoute: typeof AppInvoicingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dealers': {
      id: '/_app/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof AppDealersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDealersRoute: typeof AppDealersRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicingRoute: typeof AppInvoicingRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDealersRoute: AppDealersRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicingRoute: AppInvoicingRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppProductsRoute: AppProductsRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
